const { test, expect } = require('playwright/test');
async function category(page,name){await page.goto('/');await page.getByRole('button',{name:new RegExp(name)}).click()}
async function quick(page,task='Toilet seat',qty='1'){await category(page,'Quick Fixes');const box=page.locator(`.quickPrimaryTask[data-task="${task}"]`);await box.check();await box.locator('xpath=ancestor::*[contains(@class,"qty-row")]').locator('.quickPrimaryQty').selectOption(qty)}
async function capacity(page,required,selected){await page.goto('/');await page.evaluate(({required,selected})=>{primary={name:'Capacity test scope',price:500,displayMins:required,internalMins:required,flags:[],photo:'',invasive:false};capacityPlan={mode:'split',days:[{day:1,date:'2099-08-20',start:'08:00',end:'12:00',availableAppointmentMinutes:Math.min(240,selected),allocatedLaborMinutes:Math.min(240,required)},{day:2,date:'2099-08-21',start:'08:00',end:'17:00',availableAppointmentMinutes:Math.max(0,selected-240),allocatedLaborMinutes:Math.max(0,required-240)}],totalAvailableMinutes:selected,estimatedLaborMinutes:required,availabilityVerified:selected>=required};goTo(7)},{required,selected})}

test('Split 8.2 hours with excess capacity has functional authorization action',async({page})=>{await capacity(page,492,720);await expect(page.locator('#confirmButton')).toBeVisible();await expect(page.locator('#confirmButton')).toBeEnabled();expect((await page.evaluate(()=>__V166__.capacityEligibility())).authorizationEligible).toBe(true);await page.locator('#confirmButton').click();await expect(page.locator('#confirmState')).toContainText('CONFIRMED');await expect(page.locator('#confirmState .request-id')).toBeVisible();await expect(page.locator('#step7 [data-go="6"]')).toBeHidden()});
test('Split 9.0 hours with exact capacity has authorization action',async({page})=>{await capacity(page,540,540);await expect(page.locator('#confirmButton')).toBeVisible();expect((await page.evaluate(()=>__V166__.capacityEligibility())).remainingCapacityShortfallMinutes).toBe(0)});
test('Split insufficient capacity is blocked with explicit reason',async({page})=>{await page.goto('/');await page.evaluate(()=>{primary={name:'Capacity test',price:500,displayMins:540,internalMins:540,flags:[],invasive:false};capacityPlan={mode:'split',days:[],totalAvailableMinutes:480,estimatedLaborMinutes:540,availabilityVerified:true};renderConfirmation()});await expect(page.locator('#confirmButton')).toBeHidden();await expect(page.locator('#confirmState')).toContainText('does not yet provide enough')});
for(const qty of ['1','2','5','6','7','8','12','17','20','20+'])test(`Quick Fix Review quantity ${qty} stays synchronized`,async({page})=>{await quick(page,'Toilet seat',qty);await page.evaluate(()=>renderSummary());const s=page.locator('[data-qf-task="Toilet seat"]');await expect(s).toHaveValue(qty);await expect(page.locator('#summary')).toContainText(`× ${qty}`);expect(await page.locator('body').innerText()).not.toMatch(/NaN|undefined|Infinity/)});
test('Electrical Diagnostic selectors start blank',async({page})=>{await category(page,'Electrical');await page.locator('#eMode').selectOption('diag');await expect(page.locator('#eDiagArea')).toHaveValue('');await expect(page.locator('#eDiagSymptom')).toHaveValue('');await expect(page.locator('#eDiagQty')).toHaveValue('')});
test('Electrical Diagnostic five locations propagates without auto Review',async({page})=>{await category(page,'Electrical');await page.locator('#eMode').selectOption('diag');await page.locator('#eDiagArea').selectOption('Outlet / receptacle');await page.locator('#eDiagSymptom').selectOption('No power');await page.locator('#eDiagQty').selectOption('5');await page.evaluate(()=>{calcPrimary();renderSummary()});await expect(page.locator('#summary')).toContainText('Affected locations');expect(await page.evaluate(()=>explicitReviewReasonsV165())).toEqual([]);await page.evaluate(()=>renderConfirmation());await expect(page.locator('#confirmSummary')).toContainText('5')});
test('Furniture Review editor remains open until Done',async({page})=>{await category(page,'Furniture Assembly');const c=page.locator('.multi-item');await c.locator('.mi-type').selectOption('50,Desk');await c.locator('.mi-qty').selectOption('1');await c.locator('.mi-ready').selectOption('boxed');await page.evaluate(()=>goTo(5));await page.getByRole('button',{name:'Edit'}).click();await page.locator('.v165-multi-editor .mi-electronics').check();await expect(page.locator('.v165-multi-editor')).toBeVisible();await page.getByRole('button',{name:'Done'}).click();await expect(page.locator('.v165-multi-editor')).toHaveCount(0)});
test('Booking Confirmed is terminal with no Back button',async({page})=>{await page.goto('/');await page.evaluate(()=>renderConfirmedCard({requestId:'TEST-166',date:'2099-08-20',slot:'10:00',address:'Test address',scopeDetails:[],deposit:25,remaining:75}));await expect(page.locator('#step7 [data-go="6"]')).toBeHidden();await expect(page.locator('#confirmState')).toContainText('TEST-166')});
test('Refrigerator model reaches Review, pre-auth, and confirmed state',async({page})=>{await quick(page,'Refrigerator water filter change','1');await page.locator('.v165-have-filter').selectOption('no');await page.locator('.v165-model').fill('RF-EXAMPLE-123');await page.evaluate(()=>{__V166__.captureQuickPrimary();renderSummary()});await expect(page.locator('#summary')).toContainText('RF-EXAMPLE-123');await page.evaluate(()=>renderConfirmation());await expect(page.locator('#confirmSummary')).toContainText('RF-EXAMPLE-123');await page.evaluate(()=>renderConfirmedCard({requestId:'QF-166',date:'2099-08-20',slot:'10:00',address:'Test',scopeDetails:canonicalScopeDetails(),deposit:32.5,remaining:97.5}));await expect(page.locator('#confirmState')).toContainText('RF-EXAMPLE-123')});
test('single Quick Fix minimum presentation is truthful',async({page})=>{await quick(page);await page.evaluate(()=>renderSummary());await expect(page.locator('#summary')).toContainText('service-call minimum');await expect(page.locator('#summary')).not.toContainText('Standalone reference')});
test('Quick Fix Back reconstructs full catalog and selected state without duplication',async({page})=>{await quick(page,'Refrigerator water filter change','7');await page.locator('#detailForm .v165-have-filter').selectOption('no');await page.locator('#detailForm .v165-model').fill('MODEL-7');await page.evaluate(()=>{__V166__.captureQuickPrimary();goTo(3);goTo(5);goTo(6);goTo(5);goTo(2)});await expect(page.locator('.quickPrimaryTask')).toHaveCount(19);await expect(page.locator('.quickPrimaryTask[data-task="Refrigerator water filter change"]')).toBeChecked();await expect(page.locator('.quickPrimaryTask[data-task="Refrigerator water filter change"]').locator('xpath=ancestor::*[contains(@class,"qty-row")]').locator('.quickPrimaryQty')).toHaveValue('7');await expect(page.locator('#detailForm .v165-model')).toHaveValue('MODEL-7');const light=page.locator('.quickPrimaryTask[data-task="Change light bulb"]');await light.check();await light.locator('xpath=ancestor::*[contains(@class,"qty-row")]').locator('.quickPrimaryQty').selectOption('1');await page.evaluate(()=>{__V166__.captureQuickPrimary();renderSummary()});await expect(page.locator('#summary').getByText(/Refrigerator water filter change × 7/)).toHaveCount(1);await expect(page.locator('#summary').getByText(/Change light bulb × 1/)).toHaveCount(1)});
test('customer UI does not expose internal estimate vocabulary',async({page})=>{await capacity(page,492,600);expect((await page.locator('#confirmState,#confirmSummary,#depositBox').allInnerTexts()).join(' ')).not.toMatch(/known estimate|customer-facing estimate|qualifier controls|canonical|estimator state/i)});
test('Bundle Efficiency never compresses labor',async({page})=>{await page.goto('/');const before=await page.evaluate(()=>__V163__.laborTotal(30,'20'));await page.evaluate(()=>{BYSC_CONFIG_V162.repetitionCurve=BYSC_CONFIG_V162.repetitionCurve.map(()=>.15)});expect(await page.evaluate(()=>__V163__.laborTotal(30,'20'))).toBe(before)});

