const { test, expect } = require('playwright/test');
async function category(page,name){await page.goto('/');await page.getByRole('button',{name:new RegExp(name)}).click()}

test('one global eight-hour capacity authority',async({page})=>{await page.goto('/');expect(await page.evaluate(()=>[474,480,486,510,546,720].map(__V165__.capacityRoute))).toEqual(['standard','standard','capacity','capacity','capacity','capacity'])});
test('Preferred Day is absent and Scheduling owns date',async({page})=>{await page.goto('/');await expect(page.getByText('Preferred day',{exact:true})).toHaveCount(0);expect(await page.locator('#date').getAttribute('type')).toBe('hidden');expect((await page.evaluate(()=>__V165__.assertions())).preferredDateRemoved).toBe(true)});
test('Electrical diagnostic location count alone is not Review',async({page})=>{await category(page,'Electrical');await page.locator('#eMode').selectOption('diag');const selects=page.locator('#detailForm select:visible');for(let i=1;i<await selects.count();i++){const s=selects.nth(i);if(await s.isVisible())await s.selectOption({index:1})}expect(await page.evaluate(()=>__V165__.reviewReasons())).toEqual([])});
test('Furniture is sequential and type change invalidates only that item',async({page})=>{await category(page,'Furniture Assembly');const a=page.locator('.multi-item').first();await expect(a.locator('.mi-qty')).toBeHidden();await a.locator('.mi-type').selectOption('30,Bookcase / shelving');await expect(a.locator('.mi-qty')).toBeVisible();await a.locator('.mi-qty').selectOption('6');await a.locator('.mi-ready').selectOption('boxed');await a.locator('.mi-size').selectOption('large');await page.locator('#addMultiItem').click();const b=page.locator('.multi-item').nth(1);await b.locator('.mi-type').selectOption('18,Chair / accent chair');await b.locator('.mi-qty').selectOption('2');await b.locator('.mi-ready').selectOption('boxed');await a.locator('.mi-type').selectOption('50,Desk');await expect(a.locator('.mi-qty')).toHaveValue('');await expect(b.locator('.mi-qty')).toHaveValue('2')});
test('Bookcase descriptions remain visible in options',async({page})=>{await category(page,'Furniture Assembly');await page.locator('.mi-type').selectOption('30,Bookcase / shelving');await expect(page.locator('.mi-size option').nth(1)).toContainText('narrow / compact');await expect(page.locator('.mi-size option').nth(3)).toContainText('wide, tall')});
test('Quick Fix additions, boundaries, and one Review Remove',async({page})=>{await category(page,'Quick Fixes');for(const name of ['Change light bulb','Change HVAC filter','Refrigerator water filter change','Quick drywall patch','Range hood filter cleaning','Clean behind / under refrigerator','Connect refrigerator to existing functional water supply','Tighten or adjust furniture'])await expect(page.getByText(name,{exact:true})).toHaveCount(1);await page.getByText('Toilet seat',{exact:true}).click();await page.getByRole('button',{name:'Continue'}).click();await page.getByRole('button',{name:'Continue'}).click();await page.getByRole('button',{name:'Review Estimate'}).click();await expect(page.getByRole('button',{name:'Remove'})).toHaveCount(1);await expect(page.locator('#summary')).toContainText('Included')});
test('Refrigerator filter follow-up is conditional and required',async({page})=>{await category(page,'Quick Fixes');const box=page.locator('.quickPrimaryTask[data-task="Refrigerator water filter change"]');await box.check();await expect(page.locator('.v165-have-filter')).toBeVisible();await page.getByRole('button',{name:'Continue'}).click();await expect(page.locator('.v165-have-filter')).toHaveClass(/invalid/);await page.locator('.v165-have-filter').selectOption('no');await page.locator('.v165-cant-find').check();await page.getByRole('button',{name:'Continue'}).click();await expect(page.locator('#step3')).toBeVisible()});
test('Review never substitutes zero for unknown estimate',async({page})=>{await category(page,'Furniture Assembly');const c=page.locator('.multi-item');await c.locator('.mi-type').selectOption({label:'Nightstand'});await c.locator('.mi-qty').selectOption('1');await c.locator('.mi-ready').selectOption('boxed');await page.evaluate(()=>renderSummary());await expect(page.locator('#grandTotal')).toHaveText('Pending Review');await expect(page.locator('#summary')).not.toContainText('$0')});
test('pre-authorization has one appointment renderer',async({page})=>{await category(page,'Quick Fixes');await page.locator('.quickPrimaryTask').first().check();await page.locator('.quickPrimaryQty').first().selectOption('1');await page.evaluate(()=>{APP_STATE.scheduling={date:'2099-08-20',slot:'10:00'};selectedSlot='10:00';renderConfirmation()});await expect(page.locator('#confirmSummary').getByText('Appointment',{exact:true})).toHaveCount(1);await expect(page.locator('#confirmSummary')).toContainText('Estimated service time')});
test('no customer-visible implementation artifacts',async({page})=>{await page.goto('/');expect(await page.locator('body').innerText()).not.toMatch(/NaN|undefined|null|Infinity|Customer-facing estimate|Edit qualifier controls below/)});
test('pricing repetition does not compress labor',async({page})=>{await page.goto('/');const x=await page.evaluate(()=>({price:__V163__.priceRepeatTotal(100,'20'),labor:__V163__.laborTotal(30,'20')}));expect(x.price).toBeLessThan(2000);expect(x.labor).toBe(600)});

