const { test, expect } = require('@playwright/test');

async function category(page,name){await page.goto('/');await page.getByRole('button',{name:new RegExp(name)}).click()}

test('V1.6.3 exposes separated calculation state',async({page})=>{await page.goto('/');expect(await page.evaluate(()=>Object.keys(window.__V163__.state))).toEqual(['scope','qualifiers','pricing','repetition','labor','appointment','review','scheduling','authorization'])});
test('canonical quantities are 1-20 plus typed 20+',async({page})=>{await page.goto('/');const r=await page.evaluate(()=>[window.__V163__.quantityState('1'),window.__V163__.quantityState('20'),window.__V163__.quantityState('20+')]);expect(r[2]).toMatchObject({kind:'over-limit',exact:null,anchor:20,reviewRequired:true});expect(JSON.stringify(r)).not.toMatch(/NaN|Infinity|undefined/)});
test('price repetition resets and labor is not price-compressed',async({page})=>{await page.goto('/');const r=await page.evaluate(()=>({a:__V163__.priceRepeatTotal(100,'4'),b:__V163__.priceRepeatTotal(100,'3'),labor:__V163__.laborTotal(30,'20')}));expect(r.a+r.b).toBe(638);expect(r.labor).toBe(600)});
test('Electrical starts blank and supports multiple structured items',async({page})=>{await category(page,'Electrical');expect(await page.locator('#eMode').inputValue()).toBe('');await page.locator('#eMode').selectOption('install');await page.locator('.mi-type').selectOption('150,30,Standard light fixture');await page.locator('.mi-qty').selectOption('3');await page.locator('.mi-existing').selectOption('yes');await page.getByRole('button',{name:/Add another electrical item/}).click();const cards=page.locator('.multi-item');await cards.nth(1).locator('.mi-type').selectOption('130,15,Outlet / switch replacement');await cards.nth(1).locator('.mi-qty').selectOption('4');await cards.nth(1).locator('.mi-existing').selectOption('yes');await expect(page.locator('#livePrice')).not.toHaveText('—');expect(await page.evaluate(()=>APP_STATE.scope.items.length)).toBe(2)});
test('Furniture starts blank and supports multiple types',async({page})=>{await category(page,'Furniture Assembly');await expect(page.locator('.mi-type')).toHaveValue('');await page.locator('.mi-type').selectOption({label:'Bed / bed frame'});await page.locator('.mi-qty').selectOption('2');await page.locator('.mi-ready').selectOption('boxed');await page.getByRole('button',{name:/Add another furniture type/}).click();expect(await page.locator('.multi-item').count()).toBe(2)});
test('Review quantity remains synchronized above six',async({page})=>{await category(page,'Electrical');await page.locator('#eMode').selectOption('install');await page.locator('.mi-type').selectOption('150,30,Standard light fixture');await page.locator('.mi-qty').selectOption('12');await page.locator('.mi-existing').selectOption('yes');await page.getByRole('button',{name:'Continue'}).click();await page.getByRole('button',{name:'Continue'}).click();await page.getByRole('button',{name:'Review Estimate'}).click();await expect(page.locator('[data-multi-id]')).toHaveValue('12')});
test('20+ never leaks implementation artifacts',async({page})=>{await category(page,'Quick Fixes');await page.locator('.quickPrimaryTask').first().check();await page.locator('.quickPrimaryQty').first().selectOption('20+');expect(await page.locator('body').innerText()).not.toMatch(/NaN|undefined|null|Infinity/)});
test('Quick Fix primary hides internal allocations',async({page})=>{await category(page,'Quick Fixes');await page.locator('.quickPrimaryTask').first().check();await page.getByRole('button',{name:'Continue'}).click();await page.getByRole('button',{name:'Continue'}).click();await page.getByRole('button',{name:'Review Estimate'}).click();await expect(page.getByText(/included in your flat rate/i)).toBeVisible();await expect(page.getByText('Technician Discount',{exact:true})).toHaveCount(0)});
test('Roman shades quantity 12 skips irrelevant size question',async({page})=>{await category(page,'General Mounting');await page.locator('#mItem').selectOption({label:'Blinds / shades'});await page.locator('#mQty').selectOption('12');await expect(page.locator('#mSize')).toBeHidden();expect(await page.locator('#mSize').getAttribute('data-required')).toBe('false')});
test('clickable choice text toggles its control',async({page})=>{await category(page,'Quick Fixes');const label=page.locator('label.check').first(),box=label.locator('input');await label.locator('span').click();await expect(box).toBeChecked()});
test('authorization failure preserves state and offers retry',async({page})=>{await category(page,'Quick Fixes');await page.locator('.quickPrimaryTask').first().check();await page.getByRole('button',{name:'Continue'}).click();await page.getByRole('button',{name:'Continue'}).click();await page.getByRole('button',{name:'Review Estimate'}).click();await page.getByRole('button',{name:'Continue to schedule'}).click();await page.locator('#preferredDate').fill(new Date(Date.now()+86400000*5).toISOString().slice(0,10));await page.locator('#preferredTime').selectOption({index:1});await page.getByRole('button',{name:/Continue/}).last().click();await page.locator('#forceAuthFail').click();await page.locator('#confirmButton').click();await expect(page.locator('#confirmButton')).toHaveText(/RETRY/);await expect(page.locator('#confirmState')).toContainText('preserved');await expect(page.locator('#qaLog')).toContainText('authorization-failed')});

