const { test, expect } = require('playwright/test');
async function category(page,name){await page.goto('/');await page.getByRole('button',{name:new RegExp(name)}).click()}
async function quickReview(page,count=1){await category(page,'Quick Fixes');for(let i=0;i<count;i++)await page.locator('.quickPrimaryTask').nth(i).check();await page.getByRole('button',{name:'Continue'}).click();await page.getByRole('button',{name:'Continue'}).click();await page.getByRole('button',{name:'Review Estimate'}).click()}

test('Review renders canonical qualifier pairs',async({page})=>{await category(page,'TV Mounting');await page.locator('#tvItem').selectOption({label:'76–85 in'});await page.locator('#tvQty').selectOption('2');await page.locator('#tvWall').selectOption({index:1});await page.locator('#tvHeight').selectOption({index:1});await page.locator('#tvMount').selectOption({index:1});await page.locator('#tvCable').selectOption({index:1});await page.evaluate(()=>renderSummary());await expect(page.locator('#summary .scope-detail')).toContainText('TV size');await expect(page.locator('#summary .scope-detail')).toContainText('Wall surface')});
test('Review rerender is idempotent',async({page})=>{await quickReview(page,1);const before={rows:await page.locator('#summary .summary-row').count(),total:await page.locator('#grandTotal').textContent()};await page.evaluate(()=>renderSummary());expect({rows:await page.locator('#summary .summary-row').count(),total:await page.locator('#grandTotal').textContent()}).toEqual(before)});
test('Review Remove deletes canonical Quick Fix item',async({page})=>{await quickReview(page,2);await page.getByRole('button',{name:'Remove'}).first().click();await expect(page.locator('#detailForm .quickPrimaryTask:checked')).toHaveCount(1);await expect(page.locator('[data-qf-task]')).toHaveCount(1)});
test('Review quantity and title stay synchronized',async({page})=>{await quickReview(page,1);const select=page.locator('[data-qf-task]').first();await select.selectOption('12');await expect(select).toHaveValue('12');await expect(page.locator('#summary')).toContainText('× 12')});
test('Back from Review restores editable canonical scope',async({page})=>{await quickReview(page,1);await page.locator('#step5 [data-go="2"]').click();await expect(page.locator('#step2')).toBeVisible();await expect(page.locator('#detailForm .quickPrimaryTask:checked')).toHaveCount(1)});
test('Electrical four-item scope validates independently and preserves partial price',async({page})=>{await category(page,'Electrical');await page.locator('#eMode').selectOption('install');const data=[['130,15,Outlet replacement','4'],['130,15,Switch replacement','3'],['150,30,Standard light fixture','2'],['225,60,Ceiling fan replacement','1']];for(let i=0;i<data.length;i++){if(i)await page.locator('#addMultiItem').click();const c=page.locator('.multi-item').nth(i);await c.locator('.mi-type').selectOption(data[i][0]);await c.locator('.mi-qty').selectOption(data[i][1]);await c.locator('.mi-existing').selectOption('yes');if(i===0){await page.locator('#addMultiItem').click();await expect(page.locator('#livePrice')).toContainText('+');await page.locator('.mi-remove').last().click()}}await expect(page.locator('.multi-item')).toHaveCount(4);await expect(page.locator('#livePrice')).not.toHaveText('—');const first=page.locator('.multi-item').first();const old=await first.locator('.mi-qty').evaluate(e=>e.value);await page.locator('.multi-item').nth(1).locator('.mi-type').selectOption('145,15,Dimmer replacement');expect(await first.locator('.mi-qty').evaluate(e=>e.value)).toBe(old)});
test('Furniture per-item isolation and Bookcase size effects',async({page})=>{await category(page,'Furniture Assembly');const c=page.locator('.multi-item').first();await c.locator('.mi-type').selectOption('30,Bookcase / shelving');await c.locator('.mi-qty').selectOption('2');await c.locator('.mi-ready').selectOption('boxed');await c.locator('.mi-size').selectOption('small');const small=await page.locator('#livePrice').textContent();await c.locator('.mi-size').selectOption('large');expect(await page.locator('#livePrice').textContent()).not.toBe(small);await expect(page.getByRole('option',{name:'Nightstand'})).toHaveCount(1)});
test('Quick Fix is bookable with explicit empty reviewReason',async({page})=>{await quickReview(page,1);const d=JSON.parse(await page.locator('#v164Diagnostics').textContent());expect(d.reviewRequired).toBe(false);expect(d.reviewReason).toEqual([])});
test('quantity 20 is bookable while 20+ is explicit review',async({page})=>{await category(page,'Quick Fixes');await page.locator('.quickPrimaryTask').first().check();await page.locator('.quickPrimaryQty').first().selectOption('20');expect(await page.locator('body').innerText()).not.toMatch(/NaN|Infinity/);await page.locator('.quickPrimaryQty').first().selectOption('20+');expect((await page.evaluate(()=>explicitReviewReasonsV165())).join(' ')).toMatch(/above 20/i)});
test('Plumbing and TV show known minimum before quantity',async({page})=>{await category(page,'Plumbing');await page.locator('#pMode').selectOption('install');await expect(page.locator('#livePrice')).toContainText('$130');await category(page,'TV Mounting');await expect(page.locator('#livePrice')).not.toHaveText('—')});
test('repetition resets and labor remains independent',async({page})=>{await page.goto('/');const x=await page.evaluate(()=>({a:__V163__.priceRepeatTotal(100,'4'),b:__V163__.priceRepeatTotal(100,'3'),labor:__V163__.laborTotal(30,'20')}));expect(x.a+x.b).toBe(578);expect(x.labor).toBe(600)});
test('global capacity boundary is authoritative',async({page})=>{await page.goto('/');expect(await page.evaluate(()=>[__V164__.capacityRoute(480),__V164__.capacityRoute(481)])).toEqual(['standard','capacity'])});
test('Pacific same-day tolerance boundary',async({page})=>{await page.goto('/');const r=await page.evaluate(()=>{const p=__V164__.pacificParts(),slot=n=>{const m=p.minutes+n;return `${String(Math.floor(m/60)%24).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`};return [84,85,89,90].map(n=>__V164__.validateLeadTime(p.date,slot(n)).valid)});expect(r).toEqual([false,true,true,true])});
test('future date is unaffected by same-day lead time',async({page})=>{await page.goto('/');expect(await page.evaluate(()=>__V164__.validateLeadTime('2099-01-01','00:00').valid)).toBe(true)});
test('General Mounting shades suppress size and remain sequential',async({page})=>{await category(page,'General Mounting');await page.locator('#mItem').selectOption('Blinds / shades');await page.locator('#mQty').selectOption('12');await expect(page.locator('#mSize')).toBeHidden();await expect(page.locator('#mLocation')).toBeVisible();await expect(page.locator('#mPlane')).toBeHidden()});
test('Test Mode exposes required diagnostics',async({page})=>{await page.goto('/');const d=JSON.parse(await page.locator('#v164Diagnostics').textContent());expect(d.businessTimezone).toBe('America/Los_Angeles');expect(d).toHaveProperty('calculationTrace');expect(d).toHaveProperty('reviewReason');expect(d.pricing).toHaveProperty('bundleEfficiencySanityCheck')});

